Collections:
  - Name: SPOS
    Metadata:
      Training Data:
      - ImageNet-1k
    Paper:
      URL: https://arxiv.org/abs/1904.00420
      Title: Single Path One-Shot Neural Architecture Search with Uniform Sampling
    README: configs/nas/spos/README.md
    Code:
      URL: https://github.com/open-mmlab/mmrazor/blob/v0.1.0/mmrazor/models/algorithms/spos.py
      Version: v0.1.0
    Converted From:
      Code: https://github.com/megvii-model/SinglePathOneShot
Models:
  - Name: spos_subnet_shufflenetv2_8xb128_in1k
    In Collection: SPOS
    Metadata:
      FLOPs: 330 MB
      Supernet: ShuffleNetV2
      Mutable: https://download.openmmlab.com/mmrazor/v0.1/nas/spos/spos_shufflenetv2_subnet_8xb128_in1k/spos_shufflenetv2_subnet_8xb128_in1k_flops_0.33M_acc_73.87_20211222-454627be_mutable_cfg.yaml
    Results:
    - Task: Image Classification
      Dataset: ImageNet-1k
      Metrics:
        Top 1 Accuracy: 73.87
        Top 5 Accuracy: 91.60
    Config: configs/nas/spos/spos_subnet_shufflenetv2_8xb128_in1k.py
    Weights: https://download.openmmlab.com/mmrazor/v0.1/nas/spos/spos_shufflenetv2_subnet_8xb128_in1k/spos_shufflenetv2_subnet_8xb128_in1k_flops_0.33M_acc_73.87_20211222-1f0a0b4d.pth
