Collections:
- Name: AutoSlim
  Metadata:
    Training Data:
    - ImageNet-1k
  Paper:
    URL: https://arxiv.org/abs/1903.11728
    Title: AutoSlim:Towards One-Shot Architecture Search for Channel Numbers
  README: configs/nas/spos/README.md
  Code:
    URL: https://github.com/open-mmlab/mmrazor/blob/v0.1.0/mmrazor/models/algorithms/autoslim.py
    Version: v0.1.0
  Converted From:
    Code: https://github.com/JiahuiYu/slimmable_networks
Models:
- Name: autoslim_mbv2_subnet_8xb256_in1k
  In Collection: AutoSlim
  Metadata:
    Flops(G): 0.53
    Params(M): 6.5
    Supernet: MobileNet v2(x1.5)
    Channel: https://download.openmmlab.com/mmrazor/v0.1/pruning/autoslim/autoslim_mbv2_subnet_8xb256_in1k/autoslim_mbv2_subnet_8xb256_in1k_flops-0.53M_acc-74.23_20211222-e5208bbd_channel_cfg.yaml
  Results:
  - Task: Image Classification
    Dataset: ImageNet-1k
    Metrics:
      Top 1 Accuracy: 74.23
      Top 5 Accuracy: 91.74
  Config: configs/pruning/autoslim/autoslim_mbv2_subnet_8xb256_in1k.py
  Weights: https://download.openmmlab.com/mmrazor/v0.1/pruning/autoslim/autoslim_mbv2_subnet_8xb256_in1k/autoslim_mbv2_subnet_8xb256_in1k_flops-0.53M_acc-74.23_20211222-e5208bbd.pth
- Name: autoslim_mbv2_subnet_8xb256_in1k
  In Collection: AutoSlim
  Metadata:
    Flops(G): 0.32
    Params(M): 5.77
    Supernet: MobileNet v2(x1.5)
    Channel: https://download.openmmlab.com/mmrazor/v0.1/pruning/autoslim/autoslim_mbv2_subnet_8xb256_in1k/autoslim_mbv2_subnet_8xb256_in1k_flops-0.32M_acc-72.73_20211222-b5b0b33c_channel_cfg.yaml
  Results:
  - Task: Image Classification
    Dataset: ImageNet-1k
    Metrics:
      Top 1 Accuracy: 72.73	
      Top 5 Accuracy: 90.83
  Config: configs/pruning/autoslim/autoslim_mbv2_subnet_8xb256_in1k.py
  Weights: https://download.openmmlab.com/mmrazor/v0.1/pruning/autoslim/autoslim_mbv2_subnet_8xb256_in1k/autoslim_mbv2_subnet_8xb256_in1k_flops-0.32M_acc-72.73_20211222-b5b0b33c.pth
- Name: autoslim_mbv2_subnet_8xb256_in1k
  In Collection: AutoSlim
  Metadata:
    Flops(G): 0.22
    Params(M): 4.13
    Supernet: MobileNet v2(x1.5)
    Channel: https://download.openmmlab.com/mmrazor/v0.1/pruning/autoslim/autoslim_mbv2_subnet_8xb256_in1k/autoslim_mbv2_subnet_8xb256_in1k_flops-0.22M_acc-71.39_20211222-43117c7b_channel_cfg.yaml.?
  Results:
  - Task: Image Classification
    Dataset: ImageNet-1k
    Metrics:
      Top 1 Accuracy: 74.23
      Top 5 Accuracy: 91.74
  Config: configs/pruning/autoslim/autoslim_mbv2_subnet_8xb256_in1k.py
  Weights: https://download.openmmlab.com/mmrazor/v0.1/pruning/autoslim/autoslim_mbv2_subnet_8xb256_in1k/autoslim_mbv2_subnet_8xb256_in1k_flops-0.22M_acc-71.39_20211222-43117c7b.pth