Collections:
  - Name: AutoSlim
    Metadata:
      Training Data:
        - ImageNet-1k
    Paper:
      URL: https://arxiv.org/abs/1903.11728
      Title: AutoSlim:Towards One-Shot Architecture Search for Channel Numbers
    README: configs/nas/mmcls/autoslim/README.md
    Code:
      URL: https://github.com/open-mmlab/mmrazor/blob/v0.1.0/mmrazor/models/algorithms/autoslim.py
      Version: v0.1.0
    Converted From:
      Code: https://github.com/JiahuiYu/slimmable_networks
Models:
  - Name: autoslim_mbv2_1.5x_subnet_8xb256_in1k_flops-530M
    In Collection: AutoSlim
    Metadata:
      Flops(G): 0.53
      Params(M): 6.5
      Supernet: MobileNet v2(x1.5)
      Channel: https://download.openmmlab.com/mmrazor/v1/autoslim/autoslim_mbv2_subnet_8xb256_in1k_flops-530M_acc-74.23_20220715-aa8754fe_subnet_cfg.yaml
    Results:
      - Task: Image Classification
        Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 74.23
          Top 5 Accuracy: 91.73
    Config: configs/nas/mmcls/autoslim/autoslim_mbv2_1.5x_subnet_8xb256_in1k_flops-530M.py
    Weights: https://download.openmmlab.com/mmrazor/v1/autoslim/autoslim_mbv2_subnet_8xb256_in1k_flops-530M_acc-74.23_20220715-aa8754fe.pth
  - Name: autoslim_mbv2_1.5x_subnet_8xb256_in1k_flops-320M
    In Collection: AutoSlim
    Metadata:
      Flops(G): 0.32
      Params(M): 5.77
      Supernet: MobileNet v2(x1.5)
      Channel: https://download.openmmlab.com/mmrazor/v1/autoslim/autoslim_mbv2_subnet_8xb256_in1k_flops-320M_acc-72.73_20220715-9aa8f8ae_subnet_cfg.yaml
    Results:
      - Task: Image Classification
        Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 72.73
          Top 5 Accuracy: 90.84
    Config: configs/nas/mmcls/autoslim/autoslim_mbv2_1.5x_subnet_8xb256_in1k_flops-320M.py
    Weights: https://download.openmmlab.com/mmrazor/v1/autoslim/autoslim_mbv2_subnet_8xb256_in1k_flops-320M_acc-72.73_20220715-9aa8f8ae.pth
  - Name: autoslim_mbv2_1.5x_subnet_8xb256_in1k_flops-220M
    In Collection: AutoSlim
    Metadata:
      Flops(G): 0.22
      Params(M): 4.13
      Supernet: MobileNet v2(x1.5)
      Channel: https://download.openmmlab.com/mmrazor/v1/autoslim/autoslim_mbv2_subnet_8xb256_in1k_flops-220M_acc-71.4_20220715-9c288f3b_subnet_cfg.yaml
    Results:
      - Task: Image Classification
        Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 71.4
          Top 5 Accuracy: 90.08
    Config: configs/nas/mmcls/autoslim/autoslim_mbv2_1.5x_subnet_8xb256_in1k_flops-220M.py
    Weights: https://download.openmmlab.com/mmrazor/v1/autoslim/autoslim_mbv2_subnet_8xb256_in1k_flops-220M_acc-71.4_20220715-9c288f3b.pth
