architecture.backbone.first_mutable:
  chosen: 16
architecture.backbone.last_mutable:
  chosen: 1984
architecture.backbone.layer1.0.depthwise_conv.conv.mutable_attrs.kernel_size:
  chosen: 3
architecture.backbone.layer1.0.mutable_expand_value:
  chosen: 1
architecture.backbone.layer1.mutable_attrs.depth:
  chosen: 1
architecture.backbone.layer1.out_channels:
  chosen: 16
architecture.backbone.layer2.0.depthwise_conv.conv.mutable_attrs.kernel_size:
  chosen: 3
architecture.backbone.layer2.0.mutable_expand_value:
  chosen: 4
architecture.backbone.layer2.mutable_attrs.depth:
  chosen: 3
architecture.backbone.layer2.out_channels:
  chosen: 24
architecture.backbone.layer3.0.depthwise_conv.conv.mutable_attrs.kernel_size:
  chosen: 3
architecture.backbone.layer3.0.mutable_expand_value:
  chosen: 6
architecture.backbone.layer3.mutable_attrs.depth:
  chosen: 3
architecture.backbone.layer3.out_channels:
  chosen: 32
architecture.backbone.layer4.0.depthwise_conv.conv.mutable_attrs.kernel_size:
  chosen: 3
architecture.backbone.layer4.0.mutable_expand_value:
  chosen: 5
architecture.backbone.layer4.mutable_attrs.depth:
  chosen: 4
architecture.backbone.layer4.out_channels:
  chosen: 64
architecture.backbone.layer5.0.depthwise_conv.conv.mutable_attrs.kernel_size:
  chosen: 3
architecture.backbone.layer5.0.mutable_expand_value:
  chosen: 4
architecture.backbone.layer5.mutable_attrs.depth:
  chosen: 4
architecture.backbone.layer5.out_channels:
  chosen: 112
architecture.backbone.layer6.0.depthwise_conv.conv.mutable_attrs.kernel_size:
  chosen: 5
architecture.backbone.layer6.0.mutable_expand_value:
  chosen: 6
architecture.backbone.layer6.mutable_attrs.depth:
  chosen: 6
architecture.backbone.layer6.out_channels:
  chosen: 216
architecture.backbone.layer7.0.depthwise_conv.conv.mutable_attrs.kernel_size:
  chosen: 3
architecture.backbone.layer7.0.mutable_expand_value:
  chosen: 6
architecture.backbone.layer7.mutable_attrs.depth:
  chosen: 1
architecture.backbone.layer7.out_channels:
  chosen: 224
architecture.input_resizer.mutable_attrs.shape:
  chosen:
  - 288
  - 288
