Collections:
  - Name: DetNAS
    Metadata:
      Training Data:
      - ImageNet-1k
      - COCO
    Paper:
      URL: https://arxiv.org/abs/1903.10979
      Title: DetNAS:Backbone Search for Object Detection
    README: configs/nas/detnas/README.md
    Code:
      URL: https://github.com/open-mmlab/mmrazor/blob/v0.1.0/mmrazor/models/algorithms/detnas.py
      Version: v0.1.0
    Converted From:
      Code: https://github.com/megvii-model/DetNAS
Models:
  - Name: detnas_subnet_frcnn_shufflenetv2_fpn_1x_coco
    In Collection: DetNAS
    Metadata:
      FLOPs(Backbone): 340 MB
      Params(Backbone): 3.35 MB
      Supernet: FRCNN-ShuffleNetV2
      Mutable: https://download.openmmlab.com/mmrazor/v0.1/nas/spos/spos_shufflenetv2_subnet_8xb128_in1k/spos_shufflenetv2_subnet_8xb128_in1k_flops_0.33M_acc_73.87_20211222-454627be_mutable_cfg.yaml
    Results:
    - Task: Object Detection
      Dataset: COCO
      Metrics:
        box AP: 37.5
    Config: configs/nas/detnas/detnas_subnet_frcnn_shufflenetv2_fpn_1x_coco.py
    Weights: https://download.openmmlab.com/mmrazor/v0.1/nas/detnas/detnas_subnet_frcnn_shufflenetv2_fpn_1x_coco/detnas_subnet_frcnn_shufflenetv2_fpn_1x_coco_bbox_backbone_flops-0.34M_mAP-37.5_20211222-67fea61f_mutable_cfg.yaml
