Collections:
  - Name: WSLD
    Metadata:
      Training Data:
        - ImageNet-1k
    Paper:
      URL: https://arxiv.org/abs/2102.00650
      Title: Rethinking Soft Labels for Knowledge Distillation:A Bias-Variance Tradeoff Perspective
    README: configs/distill/mmcls/wsld/README.md
    Code:
      URL: https://github.com/open-mmlab/mmrazor/blob/v0.1.0/mmrazor/models/losses/weighted_soft_label_distillation.py
      Version: v0.1.0
    Converted From:
      Code: https://github.com/bellymonster/Weighted-Soft-Label-Distillation
Models:
  - Name: wsld_logits_resnet34_resnet18_8xb32_in1k
    In Collection: WSLD
    Metadata:
      Location: logits
      Student:
        Config: mmcls::resnet/resnet18_8xb32_in1k.py
        Weights: https://download.openmmlab.com/mmclassification/v0/resnet/resnet18_8xb32_in1k_20210831-fbbb1da6.pth
        Metrics:
          Top 1 Accuracy: 69.90
          Top 5 Accuracy: 89.43
      Teacher:
        Config: mmcls::resnet/resnet34_8xb32_in1k.py
        Weights: https://download.openmmlab.com/mmclassification/v0/resnet/resnet34_8xb32_in1k_20210831-f257d4e6.pth
        Metrics:
          Top 1 Accuracy: 73.62
          Top 5 Accuracy: 91.59
    Results:
      - Task: Image Classification
        Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 71.54
    Config: configs/distill/mmcls/wsld/wsld_logits_resnet34_resnet18_8xb32_in1k.py
    Weights: https://download.openmmlab.com/mmrazor/v0.1/distill/wsld/wsld_cls_head_resnet34_resnet18_8xb32_in1k/wsld_cls_head_resnet34_resnet18_8xb32_in1k_acc-71.54_20211222-91f28cf6.pth
